sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
  
before_install:
#- nvm install $NODE_VERSION
#- npm install npm -g
#- npm prune
- npm install
- npm install bower -g
- bower install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run test-travis