sudo: required

dist: trusty

language: node_js

node_js:
  - "6"

services:
  - mysql

cache:
  directories:
  - node_modules
  - "$HOME/.npm"
  - "$HOME/.cache/bower"
  
before_install:
- npm install
- npm install bower -g
- npm install knex -g
- bower install

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- mysql -e "CREATE DATABASE pinyin;" -uroot
- export NODE_ENV=staging 
- knex migrate:latest

script:
- npm run test-travis
- npm run test-node