language: node_js

node_js:
  - "5"
env:
  global:
  - NODE_VERSION=6
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
  
before_install:
- nvm install $NODE_VERSION
- npm install npm -g
- npm prune
- npm install
- npm install bower -g
- bower install
script:
- npm run karma