version: '2'
services:
  pinyin_db:
    hostname: db
    container_name: pinyin_db
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "pinyin"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "docker"
      MYSQL_ROOT_PASSWORD: "root"
    restart: always
    volumes:
      - ./storage/mysql:/var/lib/mysql
  pinyin_redis:
    hostname: redis
    container_name: pinyin_redis
    image: redis:4
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./storage/redis:/data
